ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    
    application {
        modules = [ com.agrihub.platform.ApplicationKt.module ]
    }
}

agrihub {
    database {
        url = "jdbc:postgresql://localhost:5432/agrihub"
        url = ${?DATABASE_URL}
        user = "agrihub"
        user = ${?DATABASE_USER}
        password = "agrihub"
        password = ${?DATABASE_PASSWORD}
        maxPoolSize = 20
    }
    
    redis {
        url = "redis://localhost:6379"
        url = ${?REDIS_URL}
    }
    
    security {
        jwtPublicKey = ""
        jwtPublicKey = ${?JWT_PUBLIC_KEY}
        jwtPrivateKey = ""
        jwtPrivateKey = ${?JWT_PRIVATE_KEY}
    }
}
